### ISSUE TITLE
Selector does not recognize nested nodes after pressing Cancel run > Progress (...)

### ISSUE THREAD

**Issue by antibugsprays** [SLAPaper/ComfyUI-Image-Selector#3]
"Unknown error" is displayed, the console says:

```
got prompt
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "P:\cui\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "P:\cui\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "P:\cui\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "P:\cui\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "P:\cui\ComfyUI\server.py", line 472, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "P:\cui\ComfyUI\execution.py", line 598, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'MyNode'
```

The MyNode isnt the first one after / before the selector, it is an unrelated one to the part where I press the buttons

Otherwise it works fine and it is a really great addition to workflows

**Comment by SLAPaper** [comment]
Didn't find "MyNode" in the code so I have no idea where this error come from.
Could you make a minimum workflow that can reproduce this error?

**Comment by antibugsprays** [comment]
I see I made a mistake here. Posted it in the wrong extension, sorry for the confusion (it was about the comfyui image picker not selector)
