### ISSUE TITLE
Runpod docker error

### ISSUE THREAD

**Issue by usamaa-saleem** [SLAPaper/ComfyUI-Image-Selector#4]
`
2023-12-11T11:03:36.971474729Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-12-11T11:03:36.971475839Z   File "/app/ComfyUI/custom_nodes/ComfyUI-Image-Selector/_init_.py", line 162, in <module>
2023-12-11T11:03:36.971477679Z     class LatentSelector:
2023-12-11T11:03:36.971479039Z   File "/app/ComfyUI/custom_nodes/ComfyUI-Image-Selector/_init_.py", line 196, in LatentSelector
2023-12-11T11:03:36.971480359Z     def run(self, latent_image: clabc.Mapping[str, torch.Tensor],
2023-12-11T11:03:36.971481489Z TypeError: 'ABCMeta' object is not subscriptable
2023-12-11T11:03:36.971482529Z 
2023-12-11T11:03:36.971483639Z Cannot import /app/ComfyUI/custom_nodes/ComfyUI-Image-Selector module for custom nodes: 'ABCMeta' object is not subscriptable
2023-12-11T11:03:36.972591206Z ### Loading: ComfyUI-Impact-Pack (V4.38.2)
2023-12-11T11:03:37.205819679Z INFO   | f4fa13c1-c456-4dd5-8b3d-d4664250057a-e1 | Started
2023-12-11T11:03:37.631362134Z ### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
2023-12-11T11:03:37.699103709Z ### Loading: ComfyUI-Manager (V1.8.3)
2023-12-11T11:03:37.874995478Z ### ComfyUI Revision: 1793 [cdff0810] | Released on '2023-12-07'
2023-12-11T11:03:37.875759426Z 
2023-12-11T11:03:37.875765196Z Import times for custom nodes:
2023-12-11T11:03:37.875830546Z    0.0 seconds (IMPORT FAILED): /app/ComfyUI/custom_nodes/ComfyUI-Image-Selector
2023-12-11T11:03:37.875849256Z    0.2 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Manager
2023-12-11T11:03:37.875854736Z    0.7 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2023-12-11T11:03:37.875856586Z 
2023-12-11T11:03:37.877481251Z Starting server
2023-12-11T11:03:37.877486701Z 
2023-12-11T11:03:37.877488221Z To see the GUI go to: http://127.0.0.1:8188
2023-12-11T11:03:39.211407053Z got prompt
2023-12-11T11:03:39.212964258Z Error handling request
2023-12-11T11:03:39.212977668Z Traceback (most recent call last):
2023-12-11T11:03:39.212979408Z   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 433, in _handle_request
2023-12-11T11:03:39.212981158Z     resp = await request_handler(request)
2023-12-11T11:03:39.212982128Z   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_app.py", line 504, in _handle
2023-12-11T11:03:39.212983358Z     resp = await handler(request)
2023-12-11T11:03:39.212984208Z   File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
2023-12-11T11:03:39.212985378Z     return await handler(request)
2023-12-11T11:03:39.212986348Z   File "/app/ComfyUI/server.py", line 46, in cache_control
2023-12-11T11:03:39.212988148Z     response: web.Response = await handler(request)
2023-12-11T11:03:39.212989248Z   File "/app/ComfyUI/server.py", line 472, in post_prompt
2023-12-11T11:03:39.212990238Z     valid = execution.validate_prompt(prompt)
2023-12-11T11:03:39.212991048Z   File "/app/ComfyUI/execution.py", line 598, in validate_prompt
2023-12-11T11:03:39.213000498Z     class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
2023-12-11T11:03:39.213001448Z KeyError: 'ImageSelector'
2023-12-11T11:03:39.277386933Z Could not connect to ComfyUI because it is not up yet. Sleeping for 2 seconds before trying again.
2023-12-11T11:03:39.277402513Z INFO   | f4fa13c1-c456-4dd5-8b3d-d4664250057a-e1 | Finished
`

Please help me with this.

**Comment by SLAPaper** [comment]
Python version is too old, it's required Python 3.9 or above

**Comment by SLAPaper** [comment]
Since no further reaction comming, I'll close this issue for now. If you have more question to ask, feel free to reopen or open another issue.
